In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier  # Ensure xgboost is installed

# Load the dataset
df = pd.read_csv('hotel_bookings.csv')  # Replace with your actual file path

# Fill missing values
df['children'].fillna(0, inplace=True)
df['country'].fillna('Unknown', inplace=True)

# Drop non-essential columns
df.drop(columns=['agent', 'company', 'reservation_status', 'reservation_status_date'], inplace=True)

# One-hot encode categorical variables
categorical_cols = ['hotel', 'arrival_date_month', 'meal', 'country', 
                    'market_segment', 'distribution_channel', 
                    'customer_type', 'reserved_room_type', 
                    'assigned_room_type', 'deposit_type']

df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Define features and target variable
X = df.drop(columns=['is_canceled'])  # Features
y = df['is_canceled']  # Target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (optional)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Support Vector Classifier": SVC(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Train and evaluate each model
for model_name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    print(f"{model_name} Results:")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print("\n" + "="*50 + "\n")


C:\Users\Neema Mishra\AppData\Local\Temp\ipykernel_8044\2094966805.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['children'].fillna(0, inplace=True)
C:\Users\Neema Mishra\AppData\Local\Temp\ipykernel_8044\2094966805.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For

Logistic Regression Results:
[[13570  1337]
 [ 2955  6016]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.86     14907
           1       0.82      0.67      0.74      8971

    accuracy                           0.82     23878
   macro avg       0.82      0.79      0.80     23878
weighted avg       0.82      0.82      0.82     23878



Random Forest Results:
[[14082   825]
 [ 1732  7239]]
              precision    recall  f1-score   support

           0       0.89      0.94      0.92     14907
           1       0.90      0.81      0.85      8971

    accuracy                           0.89     23878
   macro avg       0.89      0.88      0.88     23878
weighted avg       0.89      0.89      0.89     23878



Decision Tree Results:
[[13145  1762]
 [ 1645  7326]]
              precision    recall  f1-score   support

           0       0.89      0.88      0.89     14907
           1       0.81      0.82      0.81      8971

    accura